server:
  error:
    whitelabel:
      enabled: false

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # see https://stackoverflow.com/questions/49110818/method-org-postgresql-jdbc-pgconnection-createclob-is-not-yet-implemented?noredirect=1&lq=1
            non_contextual_creation: true

mybatis:
  mapper-locations: classpath:mybatis/sql/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
